## เริ่มใช้ Dataframe นำเข้าเริ่มจาก List Dic

In [1]:
## นำ list เข้า dataframe เป็นได้ทั้งแนว Row และ Column
## แนว Column [  ,    ,    ,    ,]

## 1. นำ Data เข้า Dataframe pd.DataFrame(data,columns = cols)

import pandas as pd
data = [10,20,30,40,'SomO']
## df = pd.DataFrame(data,columns = ['Age'])
cols = ['Age']
df = pd.DataFrame(data,columns = cols)
df

    Age
0    10
1    20
2    30
3    40
4  SomO

In [2]:
## นำ list เข้า dataframe 2  
## แนว row [[row0  ,row0, row0],[row1  ,row1, row1],[row2  ,row2, row2]]

import pandas as pd
data3 = [['คีย์บอร์ด','อุปกรณ์คอม',1200],['ตุ๊กตา','ของเล่น',1300],['Sumsung S20','มือถือ',40000]]
cols = ['สินค้า','ประเภท','ราคา']
df3 = pd.DataFrame(data3,columns = cols)
df3

        สินค้า      ประเภท   ราคา
0    คีย์บอร์ด  อุปกรณ์คอม   1200
1       ตุ๊กตา     ของเล่น   1300
2  Sumsung S20      มือถือ  40000

In [3]:
## นำ list เข้า dataframe 3  
import pandas as pd

Product1 = ['คีย์บอร์ด','ตุ๊กตา','Sumsung S20']
Category1 = ['อุปกรณ์คอม','ของเล่น','มือถือ']
Price1 = [1200,1300,40000]

## คำสั่ง Zip จะรวม product category price =1 row ไปเรื่อยๆ จะเป็น object อ่านไม่ออก 
## ต้องครอบด้วย list จะเป็น list ของ tuple 
data4 =list(zip(Product1 ,Category1,Price1))
## data 4

cols = ['สินค้า','ประเภท','ราคา']
df4 = pd.DataFrame(data4,columns = cols)
df4

        สินค้า      ประเภท   ราคา
0    คีย์บอร์ด  อุปกรณ์คอม   1200
1       ตุ๊กตา     ของเล่น   1300
2  Sumsung S20      มือถือ  40000

In [4]:
##  นำ Dic เข้า dataframe 1  
## list ครอบด้วย Dic [{ index : data, index : data },{ index : data, index : data }]
import pandas as pd

data =[{ 'productname' :'sumsung s20','category' :'มือถือ', 'price' : 50000},{'productname' : 'ส้มโอ', 'category' : 'ผลไม้', 'price' : 150},{'productname': 'พี่ปู', 'category' : 'อาหารทะเล', 'price' : 300}]

df1 = pd.DataFrame(data)
df1

   productname   category  price
0  sumsung s20     มือถือ  50000
1        ส้มโอ      ผลไม้    150
2        พี่ปู  อาหารทะเล    300

In [5]:
##  นำ Dic เข้า dataframe 2 
## Dic  { index : ชี้ไป [list],index : ชี้ไป [list],index : ชี้ไป [list]}
import pandas as pd

data = {'productname' : ['Samsung S20','ตุ๊กตา','ส้มโอ','พี่ปู'], 'category' : ['มือถือ','ของเล่น','ผลไม้','อาหารทะเล'], 'price' : [50000,200,100,300]}

df1 = pd.DataFrame(data)
## df1 = df1.set_index(['productname'])     ## ลองกำหนด productname เป็น index
df1

   productname   category  price
0  Samsung S20     มือถือ  50000
1       ตุ๊กตา    ของเล่น    200
2        ส้มโอ      ผลไม้    100
3        พี่ปู  อาหารทะเล    300

## Read Write File จาก Pandas

In [ ]:
## อ่านไฟล์ Excel  CSV Parquet
## data1 = pd.read_csv(r'path')
## data2 = pd.read_excel(r'path')
## data3 = pd.read_parquet(r'path')

import pandas as pd
data1 = pd.read_csv(r'D:\text.csv')
data2 = pd.read_excel(r'D:\test.xlsx',sheet_name='Sheet1')  ## มีหลาย sheet ระบุชื่อ sheet ให้ถูกต้อง

## cols = ['productname','category']
## data2 = pd.read_excel(r'D:\test.xlsx',sheet_name='Sheet1',usecols = cols)   ## เอาเฉพาะ column ที่จะใช้

## pip install pyarrow
## จะทำให้คุณสามารถอ่านและเขียนไฟล์ Parquet ได้โดยตรงใน Python รวมถึงทำงานร่วมกับ Pandas และ NumPy ได้อย่างสะดวก
data3 = pd.read_parquet(r'D:\test.parquet')

In [ ]:
data1
## data2
## data3

In [ ]:
## Save file  Excel CSV  Parquet 
## df.to_csv
## df.to_excel
## df.to_parquet

import pandas as pd

data2.to_csv(r'D:\Save_CSV1.csv',encoding = 'utf-8-sig',index = True, header = True)
data3.to_excel(r'D:\Save_Excel1.xlsx',sheet_name='product')
data1.to_parquet(r'D:\Save_Parquet1.parquet')

## แปลงจาก Dataframe เป็น Numpy array

In [18]:
## จะได้เป็น array  list ของ data แต่ละ row
## ข้อดีคือสามารถทำงานแบบเวกเตอร์ (vectorized operations) ได้ เช่น บวก ลบ คูณ หาร ทั้งแถวในครั้งเดียว

## data1.to_numpy(dtype =object)  บังคับให้ object บางทีมีตัวเลขและข้อความ
data1.to_numpy()         ## ระบบจะเลือกให้ตามความเหมาะสม

array([['Samsung S20', 'มือถือ', 50000],
       ['ตุ๊กตา', 'ของเล่น', 200],
       ['ส้มโอ', 'ผลไม้', 100],
       ['พี่ปู', 'อาหารทะเล', 300]], dtype=object)

## การตรวจสอบ Check ข้อมูลใน Pandas DataFrame

In [2]:
##  สำรวจ Null และ Column  dtype ด้วยคำสั่ง df.info()
import pandas as pd
df1 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name ='Sales Data')
df1.info()                              ## บอกค่าที่ไม่ใช่ null  มีกี่ column มี dtype column เป็นอะไร
## df1['Sale Price'].info()             ## สามารถดูเป็นราย column ได้

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction Date  1000 non-null   datetime64[ns]
 1   Product ID        1000 non-null   int64
 2   Quantity Sold     1000 non-null   int64
 3   Sale Price        1000 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 31.4 KB

In [3]:
## สำรวจข้อมูลอื่นๆ 

## df1.head()                   ## จากบน       สามารถใส่ตัวเลขจำนวนที่ต้องการในวงเล็บได้
## df1.tail()                ## จากด้านล่าง    สามารถใส่ตัวเลขจำนวนที่ต้องการในวงเล็บได้
## df1.sample()              ## สุ่ม           สามารถใส่ตัวเลขจำนวนที่ต้องการในวงเล็บได้
## df1.describe()            *** ค่าเฉลี่ยสถิติต่างๆ 
## df1.shape
## df1['Sale Price'].dtype     ## ต้องระบุ column ที่จะดู dtype
## df1.columns                 ## มีชื่อ column อะไรบ้าง
## df1.index                   ## ยังไม่มีการกำหนด index
## df1 = df1.set_index(['Transaction Date'])   ## สามารถกำหนด index ได้

In [7]:
## หาค่าเฉลี่ย สถิติ ต่างๆ   numeric_only = True แก้ปัญหาพวก dtype ที่มีปัญหาให้มันคำนวนได้
## mean()
## max()
## min()
## count()
## std()
## sum()

df1.mean(numeric_only = True)

Product ID        25.94300
Quantity Sold      5.51300
Sale Price       254.20032
dtype: float64

In [12]:
## นำ sale price index ที่ 1 หรือ row 2 / ค่าเฉลี่ย sale price
df1['Sale Price'][1]/df1['Sale Price'].mean()*100

140.84167950693373

## เปลี่ยน dtype ของ Column ด้วย .astype

In [ ]:
## pandas dtype
## Int64
## Float64
## string แนะนำใช้ก่อน object
## boolean
## datetime64[ns]
## datetime64[ns]
## category

df1['Transaction Date'] = df1['Transaction Date'].astype('datetime64[ns]')

In [ ]:
df1['Sale Price'] = df1['Sale Price'].astype('Float64')

In [ ]:
df1['Product ID'] = df1['Product ID'].astype('string')

## การเลือก Column และช่วงข้อมูล

In [ ]:
## หลักการหน้า Index หลัง index-1

## df1[0:3]              ## ไม่ระบุ column กรณีระบุ column df [[ column1,column2 ]]
## df1[:3]                  ## ตั้งแต่แรก ถึง index 2
## df1[:]                   ## ทั้งหมด 
## df1[['Transaction Date','Sale Price']][1:9]       ## แบบเลือก column index ไว้หน้าหรือหลังได้เหมือนกัน
## df1[1:9][['Transaction Date','Sale Price']]       ## แบบเลือก column index ไว้หน้าหรือหลังได้เหมือนกัน

In [19]:
## การใช้ loc และ iloc
## df1.loc[index:index-1]
## df1.loc[index:index-1] [[  'column1','column2' ]]
## df1.iloc[index:index-1,indexcolumn เริ่มจาก 0 : indexcolumn-1)

## df1.loc[1:3]
## df1.loc[1:3][['Transaction Date','Sale Price']]
## df1.iloc[1:3,0:3]

         Transaction Date  Product ID  Quantity Sold  Sale Price
1 2023-10-28 09:45:09.488          35              1      358.02
2 2023-10-28 09:45:09.488          42              6      207.76

## การค้นหาข้อความใน Column

In [ ]:
df2 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name ='Customer Profile')
df2

In [22]:
df2['Name'] = df2['Name'].astype('string')
df2['Gender'] = df2['Gender'].astype('string')
df2['Age'] = df2['Age'].astype('Int64')
df2['Occupation'] = df2['Occupation'].astype('string')

In [ ]:
df2.info()

In [ ]:
## การค้นหายข้อความ type ควรเป็น string หรือ object
## .str.match()  ต้องตรงกันเปะ
## .str.contains() มีส่วนใดส่วนหนึ่งของคำที่ตรงกัน

## df2[df2['Name'].str.contains('David')]
## df2[df2['Occupation'].str.match('Dentist')]

## Loop บน pandas

In [ ]:
## Loop บน pandas for ตัวแปรเก็บค่า index ,ตัวแปรเก็บค่าทั้ง row ในตัวอย่างนี้มี 4 column ก็เก็บทั้งหมด in  df.iterrows()
import pandas as pd
df1 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name ='Sales Data')

for index,rows in df1.iterrows():                        ## ตัวแปร 1 , ตัวแปร 2 in dataframe. iterrows ใน pandas
    ## print('Product ID ที่',rows['Product ID'],'ชิ้น  มียอดขาย',rows['Sale Price'],' บาท') ## print ตัวแปรเก็บค่าrow[column]
    ## กรณีใช้ {} คือ placeholder เก็บค่า ต้องต่อด้วย . format(ตัวแปร rows[column],ตัวแปร rows[column]
    print('Product ID ที่ {} ชิ้น มียอดขาย {} บาท'.format(rows['Product ID'],rows['Sale Price']))

In [51]:
## ลองใช้ Loop และ if สังเกตุ 
## if( เงื่อนไข สามารถเคาะขึ้นบรรทัดใหม่ได้กรณียาวๆ มันจะเข้าใจ หากอยู่ๆ ไปขึ้นบรรทัดใหม่มันจะ error):

for index, rows in df1.iterrows():
    if (rows['Quantity Sold'] > 9 
        and rows['Sale Price'] > 430):
            print('วันที่',rows['Transaction Date'],
                  'Product ID',rows['Product ID'],
                  'ปริมาณการขาย :',rows['Quantity Sold'],'ชิ้น',
                  'ราคาขาย :',rows['Sale Price'],' บาท')

วันที่ 2023-11-12 09:45:09.488000 Product ID 50 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 448.11  บาท
วันที่ 2023-12-20 09:45:09.488000 Product ID 31 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 433.99  บาท
วันที่ 2023-12-28 09:45:09.488000 Product ID 49 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 460.03  บาท
วันที่ 2024-01-12 09:45:09.488000 Product ID 38 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 472.58  บาท
วันที่ 2024-01-17 09:45:09.488000 Product ID 50 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 430.21  บาท
วันที่ 2024-01-26 09:45:09.488000 Product ID 19 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 488.73  บาท
วันที่ 2024-02-16 09:45:09.488000 Product ID 16 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 457.51  บาท
วันที่ 2024-02-24 09:45:09.488000 Product ID 11 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 483.85  บาท
วันที่ 2024-02-24 09:45:09.488000 Product ID 17 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 461.29  บาท
วันที่ 2024-03-05 09:45:09.488000 Product ID 7 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 496.48  บาท
วันที่ 2024-04-22 09:45:09.488000 Product ID 33 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 488.88  บาท
วันที่ 2024-04-24 09:45:09.488000 Product ID 21 ปริมาณการขาย : 10 ชิ้น ราคาขาย : 432.69  บาท

## การ Filter ข้อมูล

In [ ]:
## df[ df [column] เงื่อนไข
## and ใน filter ใช้ &
## df1[  (df1[column] เงื่อนไข) & (df1[column] เงื่อนไข) & (df1[column] เงื่อนไข)  ]

##df1['Product ID'] = df1['Product ID'].astype('string')
##df1.info()

df1[(df1['Quantity Sold']<=2) & (df1['Sale Price']>=420) & (df1['Product ID'] != '46')]

In [ ]:
## การใช้ isin(ตัวแปรเก็บข้อมูล)

ID_test = ['50','40','42','35']
df1[(df1['Product ID'].isin(ID_test)) & (df1['Sale Price']>=450)]

In [36]:
import pandas as pd
data = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name ='Customer Profile')

want_Occupation = ['Broadcast journalist','Public librarian','Estate agent','Lecturer, further education']
data[(data['Occupation'].isin(want_Occupation)) & (data['Gender'] == 'Male')]

                   Name Gender  Age                   Occupation
0        Breanna Bryant   Male   56         Broadcast journalist
126   Brianna Gutierrez   Male   24  Lecturer, further education
156    Elizabeth Bishop   Male   32             Public librarian
696  Jennifer Contreras   Male   24  Lecturer, further education
927       Joseph Rhodes   Male   34         Broadcast journalist

## Filter วันที่และเวลา

In [15]:
## กรณีเป็นวันที่และเวลา  Format data เราเป็นวันที่และเวลา
## กรณีมีวันที่ และเวลา ส่วนที่เป็น column ใช้ .dt.date
##.dt.date → คืนค่าเป็น วันที่ (YYYY-MM-DD)
## .dt.year → คืนค่าเป็น ปี (เช่น 2023)
## .dt.month → คืนค่าเป็น เดือน (1–12)
## .dt.day → คืนค่าเป็น วันของเดือน (1–31)
## กรณีมีวันที่ และเวลา ส่วนที่กำหนดเงื่อนไขค่าเดียว ใช้ pd.to_datetime("วันที่เวลา").date() มีเหมือนด้านบน year month day

## เลือกค่าเดี่ยว
df1[df1['Transaction Date'] == pd.to_datetime("2023-10-28 09:45:09.488")]

## เลือกเป็นช่วง
## start = "2023-10-28 00:00:00"    ## กรณีวันเวลา แบบนี้ เทียบตรงๆ ได้เลย
## end   = "2023-10-28 23:59:59"    ## กรณีวันเวลา แบบนี้ เทียบตรงๆ ได้เลย
## df1[(df1['Transaction Date'] >= start) & (df1['Transaction Date'] <= end)]


## กรณีเป็นวันที่อย่างเดียว  
## df1[df1['Transaction Date'].dt.date == pd.to_datetime("2023-10-28").date()]

## เลือกเป็นช่วง
## start = '2023-10-28'   ## ตรงนี้เป็น str ค่าเดียวต้องแปลง pd.to_datetime("วันที่").date() เป็นวันที่
## end =   '2023-11-03'     ## ตรงนี้เป็น str ค่าเดียวต้องแปลง pd.to_datetime("วันที่").date() เป็นวันที่
## df1[(df1['Transaction Date'].dt.date >= pd.to_datetime(start).date()) & (df1['Transaction Date'].dt.date <= pd.to_datetime(end).date())]

         Transaction Date  Product ID  Quantity Sold  Sale Price
0 2023-10-28 09:45:09.488          50              4       11.87
1 2023-10-28 09:45:09.488          35              1      358.02
2 2023-10-28 09:45:09.488          42              6      207.76
3 2023-10-28 09:45:09.488          19              5       17.01
4 2023-10-28 09:45:09.488          46              3      204.31
5 2023-10-28 09:45:09.488          22              5      359.88
6 2023-10-28 09:45:09.488           7              4      388.84

## Filtering and Sorting Data

In [ ]:
df1[(df1['Transaction Date'] >= '2024-04-20') & (df1['Transaction Date'] <  '2024-04-21')]

In [ ]:
df1[(df1['Quantity Sold']<=2) & (df1['Sale Price'] > 470)]

In [ ]:
df1[(df1['Quantity Sold']<=2) | (df1['Sale Price'] > 470)]

In [ ]:
df1[df1['Quantity Sold'].isin([2,4,6])]

In [ ]:
df2.sort_values(['Age', 'Occupation'],ascending=[True, False])

In [ ]:
df1['Target_sold'] = df1['Quantity Sold'] * 1.5

In [ ]:
df1

In [ ]:
df1['Target_Quantity'] = df1['Quantity Sold'] * 1.5
df1['Target_Sales'] = df1['Target_Quantity'] * df1['Sale Price']
df1['Total_Cost'] = df1['Target_Sales'] *0.65
df1

## การเปลี่ยนชื่อ Column และ ลบ Column

In [ ]:
df1 = df1.rename(columns = {'Transaction Date' : 'Transaction_Datetime'})
df1

In [ ]:
df55 = df1.drop(['Total_Cost','Target_Quantity'],axis=1 )
df55

## ลบ Row แบบมีเงื่อนไข

In [ ]:
## ลบ Row แบบมีเงื่อนไข
df66 = df1.drop(df1[df1['Quantity Sold'] < 8].index)
df66

In [ ]:
df77 = df1[df1['Quantity Sold'] >= 8]
df77

In [ ]:
df1['totalsale'] = df1['Quantity Sold']*df1['Sale Price']
df1.sum(axis=0,numeric_only=True)

In [ ]:
df1.notnull().sum()

In [ ]:
df1.describe()

## Grouping and Aggregation

In [ ]:
## แบบง่าย
## df.groupby('Department')['Sales'].sum()

## แบบหลายค่า min max mean std
## df.groupby('Department')['Sales'].agg(['min', 'max', 'mean'])

## Concat Merging and Joining DataFrames ต่อ Dataframe และการ merge join แบบต่างๆ

In [ ]:
import pandas as pd
df5 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name = 'Sales Data Missing')
df5.head(10)

## เพิ่ม Data 2 row เข้า Dataframe
## pd.timestamp('2023-10-29 1 เว้นวรรค 00:00:00.000')
## pd.to_datetime('')

dataadd = [[pd.Timestamp('2023-10-29 09:45:09.488'),32,6,334.89],[pd.Timestamp('2023-10-29 09:45:09.488'),13,3,109.29]]
cols = ['Transaction Date','Product ID','Quantity Sold','Sale Price']
df6 = pd.DataFrame(data=dataadd,columns=cols)    ## ได้ 2 row เป็นผลลัพธ์

## การต่อ dataframe Concat รวม 2 dataframe เข้าไป
df5 = pd.concat([df5,df6],ignore_index=True)  ## เอาไฟล์ที่อ่านด้านบนมาต่อ ด้วย 2 row dataframe 6
df5

In [ ]:
## Merge  คล้าย Vlookup หลังการ merge เราสามารถดึงข้อมูลจาก Column จาก df อีกชุดมาได้
result = pd.merge(df1, df2, on='CustomerID', how='inner')

## join  ใช้ index ของ df เป็น key เท่านั้น ชะนั้นต้อง df1.set_index('Column')

In [ ]:
import pandas as pd
newdata = [['Steven Gerrard','Male',42,'Manager Football']]
cols1 = ['Name','Gender','Age','Occupation']
df3 = pd.DataFrame(data=newdata,columns=cols1)
df3

In [ ]:
df4 = pd.concat([df2,df3],ignore_index=True)
df4

In [ ]:
df5.isnull().sum()

## Handling Missing Data จัดการค่า Missing

In [ ]:
df5['Sale Price'] = df5['Sale Price'].fillna(df5['Sale Price'].mean())
df5.head(10)

In [ ]:
import pandas as pd
df5 = pd.read_excel(r'D:\Data pandas - test.xlsx',sheet_name = 'Sales Data Missing')
df5.head(8)

In [ ]:
df5 = df5.dropna()
df5.head(8)

In [ ]:
df5[df5.duplicated()]

In [ ]:
df5['Sale Price'].unique()

## Numpy Library

## Creating and Managing Arrays

In [ ]:
## สร้างจาก List ของ Python

import numpy as np
a = np.array([1, 2, 3])   # สร้าง array 1 มิติ
print(a)                  # [1 2 3]
print(a[0], a[1], a[2])   # 1 2 3

a[2] = 5                  # เปลี่ยนค่าใน array
print(a)                  # [1 2 5]
 
b = np.array([[1,2,3],[4,5,6]])    # สร้าง array 2 มิติ
print(b)                           # [[1 2 3]
                                   # [4 5 6]]


## สร้าง Array ค่าเริ่มต้นอัตโนมัติจะเหมือนกันทุกค่าใน Array
## import numpy as np
## zero = np.zeros((2,2))   # สร้าง array ที่ทุกค่าเป็น 0
## print(zero)              

## one = np.ones((3,2))     # สร้าง array ที่ทุกค่าเป็น 1
## print(one)               
 
five = np.full((3,3), 5) # สร้าง array ที่ทุกค่าเป็นเลขที่ระบุ (5)
print(five)              # [[5 5 5]
                         #  [5 5 5]
                         #  [5 5 5]]

In [ ]:
## กำหนดช่วง Array

import numpy as np
 
max_value = 4
min_value = 1
a = [1, 22, 99, 0, 6, 8, -2, 3, 4, 3, 1]
print(np.clip(a, min_value, max_value))    # [1 4 4 1 4 4 1 3 4 3 1]

## การรวมและการแยก Array (Concatenating & Splitting)
a = np.array([1, 2])
b = np.array([3, 4])

# รวม Array เข้าด้วยกัน -> [1, 2, 3, 4]
combined = np.concatenate((a, b))

result = np.split(arr, 3)  # แบ่งเป็น 3 ส่วนเท่าๆ กัน ได้ [1,2], [3,4], [5,6]

In [ ]:
## indexing and Slicing เลือกข้อมูล และ หั่นแบ่ง
## Array 1 มิติ

import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])

# Indexing
print(arr[0])       # Output: 10 (First element)
print(arr[-1])      # Output: 60 (Last element)

# Slicing
print(arr[1:4])     # Output: [20, 30, 40] (Indices 1, 2, 3)
print(arr[:3])      # Output: [10, 20, 30] (From start to index 3 exclusive)
print(arr[::2])     # Output: [10, 30, 50] (Every 2nd element)

## Array 2 มิติ

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Indexing
# Get a specific element: matrix[row, column]
print(matrix[1, 2])    # Output: 6 (Row index 1, Column index 2)

# spilit
# Extract whole rows or columns
print(matrix[0, :])    # Output: [1, 2, 3] (All columns in row 0)
print(matrix[:, 1])    # Output: [2, 5, 8] (All rows in column 1)

# Extract a submatrix
print(matrix[0:2, 1:3]) 
# Output:
# [[2, 3],
#  [5, 6]]

In [ ]:
## การจัดการและการปรับรูปทรง Array (Managing & Reshaping)
## Reshaping
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6]) # มี 6 สมาชิก (1 มิติ)
new_arr = arr.reshape(2, 3)
print(new_arr)

## การตรวจสอบคุณสมบัติของ Array (Inspecting Arrays)

In [ ]:
## shape (2, 3) คือ 2 แถว 3 คอลัมน์
## .ndim เช่น 1 มิติ, 2 มิติ
## .dtype : int64, float64
## .size : บอกจำนวนสมาชิกทั้งหมดใน Array

In [ ]:
## Mathematical Operations on Arrays  
## + - * /  **ยกกำลัง